//
// Notifier
//

export const ADD_NOTIFIER = 'ADD_NOTIFIER';
export const ADD_INTL_NOTIFIER = 'ADD_INTL_NOTIFIER';
export const CLOSE_NOTIFIER = 'CLOSE_NOTIFIER';
export const REMOVE_NOTIFIER = 'REMOVE_NOTIFIER';


//
// Characteristics
//

export const FETCH_CHARACTERISTICS_REQUEST = "FETCH_CHARACTERISTICS_REQUEST";
export const FETCH_CHARACTERISTICS_SUCCESS = "FETCH_CHARACTERISTICS_SUCCESS";
export const FETCH_CHARACTERISTICS_CANCELLED = "FETCH_CHARACTERISTICS_CANCELLED";
export const FETCH_CHARACTERISTICS_FAILURE  = "FETCH_CHARACTERISTICS_FAILURE";


//
// Items
//

export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE  = "FETCH_ITEMS_FAILURE";

export const ADD_OR_UPDATE_ITEM_REQUEST = "ADD_OR_UPDATE_ITEM_REQUEST";
export const ADD_OR_UPDATE_ITEM_SUCCESS = "ADD_OR_UPDATE_ITEM_SUCCESS";
export const ADD_OR_UPDATE_ITEM_FAILURE  = "ADD_OR_UPDATE_ITEM_FAILURE";

export const DUPLICATE_ITEM_REQUEST = "DUPLICATE_ITEM_REQUEST";
export const DUPLICATE_ITEM_SUCCESS = "DUPLICATE_ITEM_SUCCESS";
export const DUPLICATE_ITEM_FAILURE  = "DUPLICATE_ITEM_FAILURE";

export const FILTER_ITEMS  = "FILTER_ITEMS";


//
// User
//

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE  = "LOGIN_FAILURE";

export const LOGOUT  = "LOGOUT";

export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_NAVIGATION_STYLE = 'SET_NAVIGATION_STYLE';
export const SET_DETAILS_HELP_COMPLETED = 'SET_DETAILS_HELP_COMPLETED';

